version: '3.5'

services:
  client:
    image: peterdinh/client
    ports:
      - '5001:5001'
    environment:
      - NODE_ENV=development
    deploy:
      placement:
        constraints:
          - node.role==worker
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.client.frontend.rule=Host:client.$USE_HOSTNAME"
        - "traefik.client.port=5001"
        - "traefik.client.backend=client"
    networks:
      - traefik-net
      - web-net