version: '3.5'

networks:
  traefik-net:
    driver: overlay
    external: true
    
services:
  traefik:
    image: traefik:1.7
    command:
      - --docker
      - --docker.swarmMode
      - --docker.watch
      - --docker.exposedbydefault=false
      - --docker.domain=traefik.$USE_HOSTNAME
      - --api
      - --rest
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./../traefik/traefik.toml:/traefik.toml
    deploy:
      placement:
        constraints:
          - node.role==manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:traefik.$USE_HOSTNAME"
